# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2629ab9c7bc55262648573ba4997f4d1d4bd7f159db789c423f19cb71e9892eaf1d5ec52e95f447f50b1a666a525907f67772f7ac34f098cb19e55a172ffb73

test:
  secret_key_base: 02309fc91d3370921b20e842558eca1980a4ba543988e86097b4288b49422e162b30e2ebb64a99dab880470930a56b9cadbdeb0d1bc69bf05b8b65e571b8dba3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
